[color-theme]
name = 'Mukong light'

[color-theme.base]
black = '#2F0C12'  # Dark background
blue = '#2C3E50'   # Dark Blue
current-background = '#902C2A'  # Slightly lighter dark background
cyan = '#1ABC9C'   # Aqua
dim-text = '#A0A1A7'  # Dimmed text for dark theme
green = '#27AE60'
grey = '#1A1C23'  # Pitch Dark Grey
magenta = '#8E44AD'  # Violet
orange = '#E67E22'  # Dark Orange
primary-background = '$black'
purple = '#6C3483'  # Keep existing violet
red = '#8A1A1A'  # Blood Red
secondary-background = '#34495E'  # Dark secondary background
text = '#000000'  # Zed Black text for contrast
yellow = '#F39C12'  # Bright Yellow

[color-theme.syntax]
attribute = '#F39C12'  # Bright Yellow for Attributes, Constants
"bracket.color.1" = '$blue'
"bracket.color.2" = '$yellow'
"bracket.color.3" = '$purple'
"bracket.unpaired" = '$red'
builtinType = '$cyan'
comment = '#1A1C23'  # Pitch Dark Grey for Comments
constant = '#E67E22'  # Dark Orange for Constants
constructor = '$yellow'
embedded = '$cyan'
enum = '$yellow'
enum-member = '$red'
enumMember = '$red'
escape = '$cyan'
field = '$red'
function = '#F1B510'  # Darker Yellow for Function Calls
"function.method" = '$cyan'  # Aqua for Method Calls
interface = '$yellow'
keyword = '#D35400'  # Dark Orange for Keywords & Operators
"keyword.control" = '#D35400'  # Dark Orange for Keywords & Operators
method = '$cyan'  # Aqua for Method Calls
number = '#3498DB'  # Bright Blue for Numbers & Booleans
property = '#9B59B6'  # Violet for Object Properties
"punctuation.delimiter" = '$yellow'
selfKeyword = '$purple'
string = '#16A085'  # Dark Aqua for Strings
"string.escape" = '$cyan'
struct = '$yellow'
structure = '$yellow'
symbol = '$yellow'
tag = '$red'  # Blood Red for Tags
"text.reference" = '$yellow'
"text.title" = '$orange'
"text.uri" = '$cyan'
type = '$yellow'
"type.builtin" = '$cyan'
typeAlias = '$yellow'
variable = '#D5DBDB'  # Light Grey for Variables & Parameters
"variable.other.member" = '$green'
interpolatedString = '#27AE60'  # Green for Interpolated Strings

[color-theme.ui]
"activity.background" = '#2F0C12'
"activity.current" = '$green'  # Dark Green instead of white
"completion.background" = '#1C032B'
"completion.current" = '$green'  # Dark Green instead of white
"completion_lens.foreground" = '$grey'
"debug.breakpoint" = '$red'
"debug.breakpoint.hover" = '#E06C75'
"editor.background" = '#F3CDB4'
"editor.caret" = '$cyan'
"editor.current_line" = '#4C4C4C'
"editor.debug_break_line" = '#528abF37'
"editor.dim" = '#1A1C23'  # Pitch Dark Grey
"editor.drag_drop_background" = '#79c1fc55'
"editor.drag_drop_tab_background" = '#4C4C4C'
"editor.focus" = '$green'  # Dark Green instead of white
"editor.foreground" = '$text'
"editor.indent_guide" = '$grey'
"editor.link" = '$blue'
"editor.selection" = '#5A5A5A'  # Improved selection visibility
"editor.sticky_header_background" = '$black'
"editor.visible_whitespace" = '#D0D0D0'
"error_lens.error.background" = '$red'
"error_lens.error.foreground" = '$green'  # Dark Green instead of white
"error_lens.other.background" = '$red'
"error_lens.other.foreground" = '#ECF0F1'
"error_lens.warning.background" = '#FFE4B5'
"error_lens.warning.foreground" = '$yellow'
"hover.background" = '$grey'
"inlay_hint.background" = '#528abF37'
"inlay_hint.foreground" = '$green'  # Dark Green instead of white
"lapce.border" = '#1A1C23'  # Pitch Dark Grey
"lapce.button.primary.background" = '$green'
"lapce.button.primary.foreground" = '$green'  # Dark Green instead of white
"lapce.dropdown_shadow" = '#000000'
"lapce.error" = '$red'
"lapce.icon.active" = '$green'  # Dark Green instead of white
"lapce.icon.inactive" = '$grey'
"lapce.plugin.author" = '$000000'  # Zed Black instead of white
"lapce.plugin.description" = '$000000'  # Zed Black instead of white
"lapce.plugin.name" = '$000000'  # Zed Black instead of white
"lapce.remote.connected" = '$green'
"lapce.remote.connecting" = '$orange'
"lapce.remote.disconnected" = '$red'
"lapce.remote.icon" = '$000000'  # Zed Black instead of white
"lapce.remote.local" = '$blue'
"lapce.scroll_bar" = '#BDC3C7'
"lapce.tab.active.background" = '#34495E'
"lapce.tab.active.foreground" = '$000000'  # Zed Black instead of white
"lapce.tab.active.underline" = '$cyan'
"lapce.tab.inactive.background" = '#4E4E4E'
"lapce.tab.inactive.foreground" = '$000000'  # Zed Black instead of white
"lapce.tab.inactive.underline" = '#007ACC77'
"lapce.tab.separator" = '#1A1C23'  # Pitch Dark Grey
"lapce.warn" = '$yellow'
"markdown.blockquote" = '#1A1C23'  # Pitch Dark Grey
"palette.background" = '$grey'
"palette.current.background" = '$green'  # Dark Green instead of white
"palette.current.foreground" = '$black'
"palette.foreground" = '$000000'  # Zed Black instead of white
"panel.background" = '#170201'
"panel.current.background" = '$grey'
"panel.current.foreground" = '$000000'  # Zed Black instead of white
"panel.current.foreground.dim" = '#5C6370'
"panel.foreground" = '$000000'  # Zed Black instead of white
"panel.foreground.dim" = '#5C6370'
"panel.hovered.active.background" = '$dim-text'
"panel.hovered.background" = '$grey'
"panel.hovered.foreground" = '$000000'  # Zed Black instead of white
"panel.hovered.foreground.dim" = '$grey'
"source_control.added" = '$green'
"source_control.modified" = '$cyan'
"source_control.removed" = '$red'
"status.background" = '$grey'
"status.foreground" = '$000000'  # Zed Black instead of white
"status.modal.insert.background" = '$red'
"status.modal.insert.foreground" = '$black'
"status.modal.normal.background" = '$blue'
"status.modal.normal.foreground" = '$000000'  # Zed Black instead of white
"status.modal.terminal.background" = '$purple'
"status.modal.terminal.foreground" = '$000000'  # Zed Black instead of white
"status.modal.visual.background" = '$yellow'
"status.modal.visual.foreground" = '$black'
"terminal.background" = '$black'
"terminal.black" = '$black'
"terminal.blue" = '$blue'
"terminal.bright_black" = '#545862'
"terminal.bright_blue" = '$blue'
"terminal.bright_cyan" = '$cyan'
"terminal.bright_green" = '$green'
"terminal.bright_magenta" = '$magenta'
"terminal.bright_red" = '$red'
"terminal.bright_white" = '$000000'  # Zed Black instead of white
"terminal.bright_yellow" = '$yellow'
"terminal.cursor" = '$000000'  # Zed Black instead of white
"terminal.cyan" = '$cyan'
"terminal.foreground" = '$000000'  # Zed Black instead of white
"terminal.green" = '$green'
"terminal.magenta" = '$magenta'
"terminal.red" = '$red'
"terminal.white" = '$000000'  # Zed Black instead of white
"terminal.yellow" = '$yellow'
"tooltip.background" = '$grey'
"tooltip.foreground" = '$text'

[ui]
drop-shadow-width = 0
font-family = ''
font-size = 13
header-height = 35
hover-font-family = ''
hover-font-size = 0
icon-size = 0
list-line-height = 25
open-editors-visible = true
palette-width = 500
scale = 1.0
scroll-width = 10
status-height = 25
tab-close-button = 'Right'
tab-min-width = 100
tab-separator-height = 'Content'
trim-search-results-whitespace = true
