[color-theme]
name = 'Mukong absurdo'

[color-theme.base]
black = '#017AB1'
blue = '#4078F2'  # Keep existing blue
current-background = '#689794'
cyan = '#49d6e9'  # Turquoise
dim-text = '#A0A1A7'
green = '#50A14F'
grey = '#E5E5E6'
magenta = '#d33682'
orange = '#F4912D'  # Flame Orange
primary-background = '$black'
purple = '#6c71c4'  # Keep existing purple
red = '#ED3418'  # Carmine
secondary-background = '#21252B'
text = '#D1D5DB'  # Light foreground for main text
white = '#ABB2BF'
yellow = '#b58900'  # Keep existing yellow

[color-theme.syntax]
attribute = '#d5971a'  # Galliano for Attributes, Constants
"bracket.color.1" = '$blue'
"bracket.color.2" = '$yellow'
"bracket.color.3" = '$purple'
"bracket.unpaired" = '$red'
builtinType = '$cyan'
comment = '#5b858b'  # Horizon for Comments
constant = '#d5971a'  # Galliano for Constants
constructor = '$yellow'
embedded = '$cyan'
enum = '$yellow'
enum-member = '$red'
enumMember = '$red'
escape = '$cyan'
field = '$red'
function = '#16a3b6'  # Eastern Blue for Function Calls
"function.method" = '#49d6e9'  # Turquoise for Method Calls
interface = '$yellow'
keyword = '#df769b'  # Pale Violet Red for Keywords & Operators
"keyword.control" = '#df769b'  # Pale Violet Red for Keywords & Operators
method = '#49d6e9'  # Turquoise for Method Calls
number = '#7060eb'  # Cornflower Blue for Numbers & Booleans
property = '#d67e5c'  # Japonica for Object Properties
"punctuation.delimiter" = '$yellow'
selfKeyword = '$purple'
string = '#49e9a6'  # Eucalyptus for Strings
"string.escape" = '$cyan'
struct = '$yellow'
structure = '$yellow'
symbol = '$yellow'
tag = '#e66533'  # Cinnabar for Tags
"text.reference" = '$yellow'
"text.title" = '$orange'
"text.uri" = '$cyan'
type = '$yellow'
"type.builtin" = '$cyan'
typeAlias = '$yellow'
variable = '#e4b781'  # Gold Sand for Variables & Parameters
"variable.other.member" = '$green'
interpolatedString = '#16b673'  # Mountain Meadow for Interpolated Strings

[color-theme.ui]
"activity.background" = '#387C7F'
"activity.current" = '#073642'
"completion.background" = '#052D25'
"completion.current" = '#2C313A'
"completion_lens.foreground" = '#5C6370'
"debug.breakpoint" = '$red'
"debug.breakpoint.hover" = '#E06C7566'
"editor.background" = '#031417'
"editor.caret" = '#528BFF'
"editor.current_line" = '#073642'
"editor.debug_break_line" = '#528abF37'
"editor.dim" = '#5C6370'
"editor.drag_drop_background" = '#79c1fc55'
"editor.drag_drop_tab_background" = '#0b0e1455'
"editor.focus" = '#CCCCCC'
"editor.foreground" = '$white'
"editor.indent_guide" = '$grey'
"editor.link" = '$blue'
"editor.selection" = '$grey'
"editor.sticky_header_background" = '$black'
"editor.visible_whitespace" = '$grey'
"error_lens.error.background" = '#E06C7520'
"error_lens.error.foreground" = '$red'
"error_lens.other.background" = '#5C637020'
"error_lens.other.foreground" = '#5C6370'
"error_lens.warning.background" = '#E5C07B20'
"error_lens.warning.foreground" = '$yellow'
"hover.background" = '#21252B'
"inlay_hint.background" = '#528abF37'
"inlay_hint.foreground" = '$white'
"lapce.border" = '#0d3d4a'
"lapce.button.primary.background" = '#50a14f'
"lapce.button.primary.foreground" = '$black'
"lapce.dropdown_shadow" = '#000000'
"lapce.error" = '$red'
"lapce.icon.active" = '$white'
"lapce.icon.inactive" = '#5C6370'
"lapce.plugin.author" = '#B0B0B0'
"lapce.plugin.description" = '$white'
"lapce.plugin.name" = '#DDDDDD'
"lapce.remote.connected" = '#50A14F'
"lapce.remote.connecting" = '#C18401'
"lapce.remote.disconnected" = '#E45649'
"lapce.remote.icon" = '$white'
"lapce.remote.local" = '#4078F2'
"lapce.scroll_bar" = '#f8f8f8'
"lapce.tab.active.background" = '#002b36'
"lapce.tab.active.foreground" = '$white'
"lapce.tab.active.underline" = '#528BFF'
"lapce.tab.inactive.background" = '#073642'
"lapce.tab.inactive.foreground" = '$white'
"lapce.tab.inactive.underline" = '#528BFF77'
"lapce.tab.separator" = '#174c59'
"lapce.warn" = '$yellow'
"markdown.blockquote" = '#898989'
"palette.background" = '#21252B'
"palette.current.background" = '#2C313A'
"palette.current.foreground" = '$white'
"palette.foreground" = '$white'
"panel.background" = '#23777C'
"panel.current.background" = '#2C313A'
"panel.current.foreground" = '$white'
"panel.current.foreground.dim" = '#5C6370'
"panel.foreground" = '$white'
"panel.foreground.dim" = '#5C6370'
"panel.hovered.active.background" = '$dim-text'
"panel.hovered.background" = '#343A45'
"panel.hovered.foreground" = '$white'
"panel.hovered.foreground.dim" = '#5C6370'
"source_control.added" = '#50A14F32'
"source_control.modified" = '#0184BC32'
"source_control.removed" = '#FF526632'
"status.background" = '#21252B'
"status.foreground" = '$white'
"status.modal.insert.background" = '$red'
"status.modal.insert.foreground" = '$black'
"status.modal.normal.background" = '$blue'
"status.modal.normal.foreground" = '$black'
"status.modal.terminal.background" = '$purple'
"status.modal.terminal.foreground" = '$black'
"status.modal.visual.background" = '$yellow'
"status.modal.visual.foreground" = '$black'
"terminal.background" = '#002b36'
"terminal.black" = '$black'
"terminal.blue" = '$blue'
"terminal.bright_black" = '#545862'
"terminal.bright_blue" = '$blue'
"terminal.bright_cyan" = '$cyan'
"terminal.bright_green" = '$green'
"terminal.bright_magenta" = '$magenta'
"terminal.bright_red" = '$red'
"terminal.bright_white" = '#C8CCD4'
"terminal.bright_yellow" = '$yellow'
"terminal.cursor" = '$white'
"terminal.cyan" = '$cyan'
"terminal.foreground" = '$white'
"terminal.green" = '$green'
"terminal.magenta" = '$magenta'
"terminal.red" = '$red'
"terminal.white" = '$white'
"terminal.yellow" = '$yellow'
"tooltip.background" = '$primary-background'
"tooltip.foreground" = '$text'

[ui]
drop-shadow-width = 0
font-family = ''
font-size = 13
header-height = 35
hover-font-family = ''
hover-font-size = 0
icon-size = 0
list-line-height = 25
open-editors-visible = true
palette-width = 500
scale = 1.0
scroll-width = 10
status-height = 25
tab-close-button = 'Right'
tab-min-width = 100
tab-separator-height = 'Content'
trim-search-results-whitespace = true
