[color-theme]
name = "Mukong Light"

[color-theme.base]
white = "#D6DEEB"
black = "#1B2B34"
grey = "#2C3A47"
blue = "#82AAFF"
red = "#EF5350"
yellow = "#FFCB6B"
orange = "#F78C6C"
green = "#C3E88D"
purple = "#C792EA"
cyan = "#89DDFF"
magenta = "#FF5370"

[color-theme.syntax]
attribute = "$yellow"
builtinType = "$cyan"
comment = "#546E7A"
constant = "$yellow"
constructor = "$purple"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$orange"
enumMember = "$orange"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$purple"
"keyword.control" = "$purple"
method = "$blue"
number = "$yellow"
property = "$red"
"punctuation.delimiter" = "$grey"
selfKeyword = "$purple"
string = "$green"
"string.escape" = "$cyan"
struct = "$yellow"
structure = "$yellow"
symbol = "$yellow"
tag = "$blue"
"text.reference" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$yellow"
"type.builtin" = "$cyan"
typeAlias = "$yellow"
variable = "$red"
"variable.other.member" = "$green"

[color-theme.ui]
"activity.background" = "#1B2B34"
"activity.current" = "#2C3A47"
"completion.background" = "#2C3A47"
"completion.current" = "#354151"
"completion_lens.foreground" = "#546E7A"
"editor.background" = "#1B2B34"
"editor.caret" = "#FFCB6B"
"editor.current_line" = "#2C3A47"
"editor.dim" = "#546E7A"
"editor.drag_drop_background" = "#89DDFF55"
"editor.drag_drop_tab_background" = "#1B2B3455"
"editor.focus" = "#D6DEEB"
"editor.foreground" = "$white"
"editor.indent_guide" = "$grey"
"editor.link" = "$blue"
"editor.selection" = "$grey"
"editor.sticky_header_background" = "$black"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#EF535020"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#546E7A20"
"error_lens.other.foreground" = "#546E7A"
"error_lens.warning.background" = "#FFCB6B20"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#2C3A47"
"inlay_hint.background" = "#82AAFF37"
"inlay_hint.foreground" = "$white"
"lapce.border" = "#354151"
"lapce.button.primary.background" = "#C3E88D"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#546E7A"
"lapce.plugin.author" = "#B0B0B0"
"lapce.plugin.description" = "$white"
"lapce.plugin.name" = "#DDDDDD"
"lapce.remote.connected" = "#C3E88D"
"lapce.remote.connecting" = "#FFCB6B"
"lapce.remote.disconnected" = "#EF5350"
"lapce.remote.icon" = "$white"
"lapce.remote.local" = "#82AAFF"
"lapce.scroll_bar" = "#D6DEEB"
"lapce.tab.active.background" = "#1B2B34"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#82AAFF"
"lapce.tab.inactive.background" = "#2C3A47"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#82AAFF77"
"lapce.tab.separator" = "#354151"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#B0BEC5"
"palette.background" = "#2C3A47"
"palette.current.background" = "#354151"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "#2C3A47"
"panel.current.background" = "#354151"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#546E7A"
"panel.foreground" = "$white"
"panel.foreground.dim" = "#546E7A"
"panel.hovered.background" = "#546E7A"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#546E7A"
"source_control.added" = "#C3E88D32"
"source_control.modified" = "#82AAFF32"
"source_control.removed" = "#FF537032"
"status.background" = "#2C3A47"
"status.foreground" = "$white"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"terminal.background" = "#1B2B34"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#546E7A"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#D6DEEB"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
list-line-height = 25
