[color-theme]
name = 'Mukong Oceano'

[color-theme.base]
black = '#000000'  # Black
blue = '#1E3A8A'  # Dark Blue Background
current-background = '#001F55'  # Sky Blue for current background
cyan = '#06B6D4'  # Cyan
dim-text = '#A0A1A7'  # Dimmed text
green = '#10B981'  # Green
grey = '#E5E5E6'  # Light Grey
magenta = '#D5006D'  # Magenta
orange = '#F97316'  # Orange
primary-background = '$black'
purple = '#6B21A8'  # Purple
red = '#EF4444'  # Red
secondary-background = '#F7F7F7'  # Light secondary background
text = '#FFFFFF'  # White text for contrast
yellow = '#FBBF24'  # Yellow

[color-theme.syntax]
attribute = '#FBBF24'  # Yellow for Attributes, Constants
"bracket.color.1" = '$blue'
"bracket.color.2" = '$yellow'
"bracket.color.3" = '$purple'
"bracket.unpaired" = '$red'
builtinType = '$cyan'
comment = '#6B7280'  # Gray for Comments
constant = '#FBBF24'  # Yellow for Constants
constructor = '$orange'
embedded = '$cyan'
enum = '$yellow'
enum-member = '$red'
enumMember = '$red'
escape = '$cyan'
field = '$red'
function = '#3B82F6'  # Sky Blue for Function Calls
"function.method" = '#06B6D4'  # Cyan for Method Calls
interface = '$yellow'
keyword = '#D5006D'  # Magenta for Keywords & Operators
"keyword.control" = '#D5006D'  # Magenta for control keywords
method = '#06B6D4'  # Cyan for Method Calls
number = '#EF4444'  # Red for Numbers & Booleans
property = '#FBBF24'  # Yellow for Object Properties
"punctuation.delimiter" = '$yellow'
selfKeyword = '$purple'
string = '#10B981'  # Green for Strings
"string.escape" = '$cyan'
struct = '$yellow'
structure = '$yellow'
symbol = '$yellow'
tag = '#F97316'  # Orange for Tags
"text.reference" = '$yellow'
"text.title" = '$orange'
"text.uri" = '$cyan'
type = '$yellow'
"type.builtin" = '$cyan'
typeAlias = '$yellow'
variable = '#FBBF24'  # Yellow for Variables & Parameters
"variable.other.member" = '$green'
interpolatedString = '#10B981'  # Green for Interpolated Strings

[color-theme.ui]
"activity.background" = '#0F889B'  # Dark Blue
"activity.current" = '#E0E0E0'  # Light Grey
"completion.background" = '#00ADA1'  # Dark Blue
"completion.current" = '#F0F0F0'  # Light Grey
"completion_lens.foreground" = '#5C6370'
"debug.breakpoint" = '$red'
"debug.breakpoint.hover" = '#E06C7566'
"editor.background" = '#0C102B'  # Dark Blue Background
"editor.caret" = '#007ACC'  # Caret Color
"editor.current_line" = '#3B82F6'  # Sky Blue for current line
"editor.debug_break_line" = '#528abF37'
"editor.dim" = '#B0B0B0'
"editor.drag_drop_background" = '#79c1fc55'
"editor.drag_drop_tab_background" = '#E0E0E0'
"editor.focus" = '#333333'
"editor.foreground" = '$white'
"editor.indent_guide" = '$grey'
"editor.link" = '$blue'
"editor.selection" = '#FBBF24'  # Yellow for selection
"editor.sticky_header_background" = '$black'
"editor.visible_whitespace" = '#D0D0D0'
"error_lens.error.background" = '#F8D7DA'
"error_lens.error.foreground" = '$red'
"error_lens.other.background" = '#F8D7DA'
"error_lens.other.foreground" = '#5C6370'
"error_lens.warning.background" = '#FFE4B5'
"error_lens.warning.foreground" = '$yellow'
"hover.background" = '#FFFFFF'
"inlay_hint.background" = '#528abF37'
"inlay_hint.foreground" = '$black'
"lapce.border" = '#D0D0D0'
"lapce.button.primary.background" = '#10B981'  # Green for primary button
"lapce.button.primary.foreground" = '$white'
"lapce.dropdown_shadow" = '#000000'
"lapce.error" = '$red'
"lapce.icon.active" = '$black'
"lapce.icon.inactive" = '#5C6370'
"lapce.plugin.author" = '$333333'
"lapce.plugin.description" = '$black'
"lapce.plugin.name" = '#333333'
"lapce.remote.connected" = '#10B981'
"lapce.remote.connecting" = '#C18401'
"lapce.remote.disconnected" = '$red'
"lapce.remote.icon" = '$black'
"lapce.remote.local" = '#4078F2'
"lapce.scroll_bar" = '#CCCCCC'
"lapce.tab.active.background" = '#1E3A8A'  # Dark Blue
"lapce.tab.active.foreground" = '$white'
"lapce.tab.active.underline" = '#007ACC'
"lapce.tab.inactive.background" = '#1E3A8A'  # Dark Blue
"lapce.tab.inactive.foreground" = '$white'
"lapce.tab.inactive.underline" = '#007ACC77'
"lapce.tab.separator" = '#E0E0E0'
"lapce.warn" = '$yellow'
"markdown.blockquote" = '#898989'
"palette.background" = '#1E3A8A'  # Dark Blue
"palette.current.background" = '#F0F0F0'
"palette.current.foreground" = '$white'
"palette.foreground" = '$white'
"panel.background" = '#1381A2'  # Dark Blue
"panel.current.background" = '#F0F0F0'
"panel.current.foreground" = '$white'
"panel.current.foreground.dim" = '#5C6370'
"panel.foreground" = '$white'
"panel.foreground.dim" = '#5C6370'
"panel.hovered.active.background" = '$dim-text'
"panel.hovered.background" = '#F0F0F0'
"panel.hovered.foreground" = '$white'
"panel.hovered.foreground.dim" = '#5C6370'
"source_control.added" = '#50A14F32'
"source_control.modified" = '#0184BC32'
"source_control.removed" = '#FF526632'
"status.background" = '#1E3A8A'  # Dark Blue
"status.foreground" = '$white'
"status.modal.insert.background" = '$red'
"status.modal.insert.foreground" = '$white'
"status.modal.normal.background" = '$blue'
"status.modal.normal.foreground" = '$white'
"status.modal.terminal.background" = '$purple'
"status.modal.terminal.foreground" = '$white'
"status.modal.visual.background" = '$yellow'
"status.modal.visual.foreground" = '$white'
"terminal.background" = '#1E3A8A'  # Dark Blue
"terminal.black" = '$black'
"terminal.blue" = '$blue'
"terminal.bright_black" = '#545862'
"terminal.bright_blue" = '$blue'
"terminal.bright_cyan" = '$cyan'
"terminal.bright_green" = '$green'
"terminal.bright_magenta" = '$magenta'
"terminal.bright_red" = '$red'
"terminal.bright_white" = '#C8CCD4'
"terminal.bright_yellow" = '$yellow'
"terminal.cursor" = '$black'
"terminal.cyan" = '$cyan'
"terminal.foreground" = '$white'
"terminal.green" = '$green'
"terminal.magenta" = '$magenta'
"terminal.red" = '$red'
"terminal.white" = '$white'
"terminal.yellow" = '$yellow'
"tooltip.background" = '$primary-background'
"tooltip.foreground" = '$text'

[ui]
drop-shadow-width = 0
font-family = ''
font-size = 13
header-height = 35
hover-font-family = ''
hover-font-size = 0
icon-size = 0
list-line-height = 25
open-editors-visible = true
palette-width = 500
scale = 1.0
scroll-width = 10
status-height = 25
tab-close-button = 'Right'
tab-min-width = 100
tab-separator-height = 'Content'
trim-search-results-whitespace = true

