name = "Mukong Theme"
version = "0.1.1"
display-name = "Mukong Theme"
author = "Amit Gosain"
description = "Mukong theme for Lapce editor"
icon = "logo.png"
repository = "https://github.com/gosainamit/mukong"
color-themes = [
    "Mukong-Dark.toml",
    "Mukong-Light.toml",
	"Mukong-Absurdo.toml",
    "Mukong-Oceano.toml",
]
